services:
  api:
    build: .
    container_name: fastapi_app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:18.3
    container_name: postgres_db
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  nginx:
    build: nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
