"""Add email column to users.

Revision ID: 9d1cd0000340
Revises: f5ecc9d002b9
Create Date: 2026-03-19 13:14:31.416242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d1cd0000340"
down_revision: Union[str, Sequence[str], None] = "f5ecc9d002b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=64), nullable=True))
    op.execute("""
        UPDATE users
        SET email = name || '@yahoo.com'
        WHERE email IS NULL
    """)
    op.alter_column("users", "email", nullable=False)

    op.create_unique_constraint("uq_users_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
