"""Add users table.  Add owner column to notes table

Revision ID: f5ecc9d002b9
Revises:
Create Date: 2026-03-19 07:46:08.446115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5ecc9d002b9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Add users manually to link the notes to
    op.execute("""
        INSERT INTO users (name)
        VALUES
            ('Patrick'),
            ('Sandy'),
            ('Mr.Krabs')
    """)
    # Add a nullable column in order to set the values, and set it back to non-nullable
    op.add_column("notes", sa.Column("owner", sa.Integer(), nullable=True))
    op.execute("UPDATE notes SET owner = 1 WHERE id <= 3")
    op.execute("UPDATE notes SET owner = 2 WHERE id > 3")
    op.alter_column("notes", "owner", nullable=False)
    # ---------------------------------------------------------------------------------
    op.create_foreign_key("notes_owner_fkey", "notes", "users", ["owner"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("notes_owner_fkey", "notes", type_="foreignkey")
    op.drop_column("notes", "owner")
    op.drop_table("users")
    # ### end Alembic commands ###
