name: CI

on:
  push:
    branches:
      - master
      - feature/docker-compose-deployment

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      REDIS_URL: ${{ secrets.REDIS_URL_PYTEST }}
      DATABASE_URL: ${{ secrets.DATABASE_URL_PYTEST }}
      SECRET_KEY: ${{ secrets.SECRET_KEY_PYTEST }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14.4"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytests
        run: pytest
  build:
    name: Build Docker images
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Build notes-app Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notes-app:latest .
      - name: Build nginx Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest nginx/
      # - name: Tag image
      #   run: docker tag notes-app ${{ secrets.DOCKER_USERNAME }}/notes-app:latest
      # - name: Tag image
      #   run: docker tag nginx ${{ secrets.DOCKER_USERNAME }}/nginx:latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notes-app:latest
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull conraaddocker/notes-app:latest
            docker pull conraaddocker/nginx:latest

            docker stop notes-app || true
            docker rm notes-app || true

            docker run -d \
              --restart always \
              -p 8000:8000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e REDIS_URL=${{ secrets.REDIS_URL }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              --name notes-app \
              conraaddocker/notes-app:latest


            # TODO: set up nginx as well.  Most probably going to use docker-compose to set up nginx in a container alongside the fast-api container
